/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoso;

import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import recursos.jpFondoBarra;

/**
 *
 * @author fabricio
 */
public class Vista extends javax.swing.JFrame {

    public class HiloHerencia extends Thread {

        Vista vista;

        private HiloHerencia(Vista vista) {
            this.vista = vista;
        }

        public void run() {
            while (true) {
                this.vista.jl_tiempo_encendido.setText(Comando.tiempoEncendio());
            }
        }
    }

    public class HiloImplements implements Runnable {

        Vista vista;

        private HiloImplements(Vista vista) {
            this.vista = vista;
        }

        public void run() {
            while (true) {
                this.vista.jl_temperatura_cpu.setText(Comando.temperatura());
            }
        }

    }

    HiloHerencia tiempo_encendido;
    HiloImplements hiloRunnable;
    Thread temperatura_cpu;
    Thread memoria;

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        panel1 = new jpFondoBarra("../recursos/gradient1.jpg", this.getWidth(), this.getHeight());
        this.add(panel1, BorderLayout.CENTER);
        panel1.repaint();
    }

    private void tiempoEncendido() {
        this.tiempo_encendido = new HiloHerencia(this);
    }

    private void temperaturaCPU() {
        hiloRunnable = new HiloImplements(this);
        temperatura_cpu = new Thread(hiloRunnable);
    }

    private void memoria() {
        memoria = new Thread() {
            public void run() {
                while (true) {
                    jl_memoria.setText(Comando.memoria());
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jl_tiempo_encendido = new javax.swing.JLabel();
        jl_temperatura_cpu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jl_memoria = new javax.swing.JLabel();
        jbtn_iniciar = new javax.swing.JButton();
        jbtn_pausar = new javax.swing.JButton();
        jbtn_continuar = new javax.swing.JButton();
        jbtn_terminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel1.setOpaque(false);

        jl_tiempo_encendido.setBackground(new java.awt.Color(136, 131, 131));
        jl_tiempo_encendido.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jl_tiempo_encendido.setForeground(new java.awt.Color(222, 224, 238));
        jl_tiempo_encendido.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jl_tiempo_encendido.setOpaque(true);

        jl_temperatura_cpu.setBackground(new java.awt.Color(136, 131, 131));
        jl_temperatura_cpu.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jl_temperatura_cpu.setForeground(new java.awt.Color(222, 224, 238));
        jl_temperatura_cpu.setAutoscrolls(true);
        jl_temperatura_cpu.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jl_temperatura_cpu.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 196, 249));
        jLabel1.setText("TIEMPO DE ENCENDIDO:");

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 196, 249));
        jLabel2.setText("TEMPERATURA CPU:");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 196, 249));
        jLabel3.setText("MEMORIA:");

        jl_memoria.setBackground(new java.awt.Color(136, 131, 131));
        jl_memoria.setFont(new java.awt.Font("FreeSans", 1, 24)); // NOI18N
        jl_memoria.setForeground(new java.awt.Color(222, 224, 238));
        jl_memoria.setAutoscrolls(true);
        jl_memoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jl_memoria.setOpaque(true);

        jbtn_iniciar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jbtn_iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descarga.jpg"))); // NOI18N
        jbtn_iniciar.setText("INICIAR");
        jbtn_iniciar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jbtn_iniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_iniciar.setOpaque(true);
        jbtn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_iniciarActionPerformed(evt);
            }
        });

        jbtn_pausar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jbtn_pausar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descarga.jpg"))); // NOI18N
        jbtn_pausar.setText("PAUSAR");
        jbtn_pausar.setEnabled(false);
        jbtn_pausar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_pausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_pausarActionPerformed(evt);
            }
        });

        jbtn_continuar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jbtn_continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descarga.jpg"))); // NOI18N
        jbtn_continuar.setText("CONTINUAR");
        jbtn_continuar.setEnabled(false);
        jbtn_continuar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_continuarActionPerformed(evt);
            }
        });

        jbtn_terminar.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jbtn_terminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/descarga.jpg"))); // NOI18N
        jbtn_terminar.setText("TERMINAR");
        jbtn_terminar.setEnabled(false);
        jbtn_terminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_terminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jbtn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, Short.MAX_VALUE))
                    .addComponent(jl_memoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_temperatura_cpu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_tiempo_encendido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jl_tiempo_encendido, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_temperatura_cpu, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jl_memoria, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_pausar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_continuar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_iniciarActionPerformed
        tiempoEncendido();
        temperaturaCPU();
        memoria();
        jbtn_pausar.setEnabled(true);
        jbtn_terminar.setEnabled(true);
        jbtn_iniciar.setEnabled(false);
        tiempo_encendido.start();
        temperatura_cpu.start();
        memoria.start();
    }//GEN-LAST:event_jbtn_iniciarActionPerformed

    private void jbtn_continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_continuarActionPerformed

        jbtn_pausar.setEnabled(true);
        jbtn_continuar.setEnabled(false);
        tiempo_encendido.resume();
        temperatura_cpu.resume();
        memoria.resume();

    }//GEN-LAST:event_jbtn_continuarActionPerformed

    private void jbtn_pausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_pausarActionPerformed
        jbtn_continuar.setEnabled(true);
        jbtn_pausar.setEnabled(false);
        tiempo_encendido.suspend();
        temperatura_cpu.suspend();
        memoria.suspend();
    }//GEN-LAST:event_jbtn_pausarActionPerformed

    private void jbtn_terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_terminarActionPerformed
        
        
        jbtn_pausar.setEnabled(false);
        jbtn_continuar.setEnabled(false);
        jbtn_terminar.setEnabled(false);
        jbtn_iniciar.setEnabled(true);
        tiempo_encendido.stop();
        temperatura_cpu.stop();
        memoria.stop();
jl_memoria.setText("");
        jl_temperatura_cpu.setText("");
        jl_tiempo_encendido.setText("");
    }//GEN-LAST:event_jbtn_terminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbtn_continuar;
    private javax.swing.JButton jbtn_iniciar;
    private javax.swing.JButton jbtn_pausar;
    private javax.swing.JButton jbtn_terminar;
    private javax.swing.JLabel jl_memoria;
    private javax.swing.JLabel jl_temperatura_cpu;
    private javax.swing.JLabel jl_tiempo_encendido;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
